### ISSUE TITLE
Associate Array binding - model update is not syncing with the view

### ISSUE THREAD

**Issue by chandmk** [aurelia/templating-binding#26] opened 2015-04-18 11:52 UTC
Version: 0.12

``` javasscript
export class Test {
  Data = [[0,1],[2,3]]

  addone() {
    this.Data[0][0]++;
  }
}
```

``` html
<template>
<input type="text" value.bind="Data[0][0]" />
  <button click.trigger="addone()" value="Add One" >Add One </button>
</template>
```

When I click AddOne button, I am expecting that cell to have its value incremented by 1.

**Comment by jdanyow** [comment] 2015-04-19 02:08
duplicate of https://github.com/aurelia/binding/issues/64

**Comment by chandmk** [comment] 2015-04-19 14:19
Then, is the following code idiomatic in aurelia?

``` javascript
export class Test {
  Data = [[0,1],[2,3]]

  addone(evt) {
   evt.target.value++;
  }
}
```

``` html
<template>
<input type="text" value.bind="Data[0][0]" />
  <button click.trigger="addone($event)" value="Add One" >Add One </button>
</template>
```

**Comment by jdanyow** [comment] 2015-04-20 01:32
Per https://github.com/aurelia/binding/issues/64, no, it is not idiomatic to bind to a particular index of an array and be updated when the value stored at that index changes.

Please review the comments in https://github.com/aurelia/binding/issues/64 for more details.

**Closed as completed** 2015-04-22 05:42 UTC
Labels: duplicate
