### ISSUE TITLE
request binding warnings/errors if the binding attribute does not exist

### ISSUE THREAD

**Issue by CarlosOnline** [aurelia/templating-binding#40] opened 2015-05-27 15:18 UTC
for example missPellage doesn't exist on the view model, but no warning/error is reported.

Would be nice to see the misspelled binding even if just in debug mode.

```
<div show.bind="missPellage">
</div>
```

**Comment by jdanyow** [comment] 2015-05-29 02:48
duplicate of https://github.com/aurelia/binding/issues/30

**Closed as completed by jdanyow** 2015-05-29 02:48 UTC
Labels: duplicate
